spring:
  flyway:
    locations:
      - classpath:db/migration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demo-app
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
