apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecAuditEngine RelevantOnly
      SecAuditLog /var/log/sec_audit.log
      SecAuditLogParts ACH
      SecRequestBodyAccess On
      SecRule ARGS|REQUEST_BODY "@contains \' or 2>1--" "id:2,deny,log,status:999"
      SecRule ARGS|REQUEST_BODY "@contains ../../../../../etc/passwd" "id:3,deny,log,status:999"
      SecRule ARGS|REQUEST_BODY "@contains ls -la" "id:5,phase:request,log"
spec:
  rules:
    - http:
        paths:
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: static-app-service
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: task-app-service
                port:
                  number: 8080
